version: '3.8'

services:
    postgres:
        image: postgres:16.0-alpine3.18
        restart: always
        env_file:
            - .env/.env.postgres
        volumes:
            - postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:7.8
        restart: always
        env_file:
            - .env/.env.pgadmin
        ports:
            - 15432:80
        volumes:
            - pgadmin:/var/lib/pgadmin
        depends_on:
            - postgres

    backend-fs:
        image: ghcr.io/go-park-mail-ru/2023_2_rabotyagi:fs-latest-dev
        restart: always
        env_file:
            - .env/.env.fs

        expose:
            - 8081
            - 8011
        depends_on:
            - postgres
        volumes:
            - ./static/imgs:/var/file_service/static/img
            - log-fs:/var/log/backend

    backend-auth:
        image: ghcr.io/go-park-mail-ru/2023_2_rabotyagi:auth-latest-dev
        restart: always
        env_file:
            - .env/.env.auth
        expose:
            - 8012
            - 8011
        depends_on:
            - postgres
        volumes:
            - log-auth:/var/log/backend

    backend:
        image: ghcr.io/go-park-mail-ru/2023_2_rabotyagi:main-latest-dev
        restart: always
        env_file:
            - .env/.env.main
        expose:
            - 8080
        depends_on:
            - postgres
            - backend-fs
            - backend-auth
        volumes:
            - log:/var/log/backend

    nginx:
        image: nginx:stable
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:80

volumes:
    postgres:
    pgadmin:
    log:
    log-fs:
    log-auth:
