name: build-push-dev

on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]
        types:
            - closed
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{github.repository}}
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to the Github Container registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract Docker metadata
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

            - name: Write tags to env variables
              run: |
                  echo "IMAGE_TAGS=${{steps.meta.outputs.tags}}" >> $GITHUB_ENV

            - name: Build and push
              uses: docker/build-push-action@v5
              id: build
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}

            - name: Send Good Notification
              uses: appleboy/telegram-action@master
              if: success()
              with:
                  to: ${{ secrets.TELEGRAM_CHAT }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  format: markdown
                  message: |
                      Билд образа ${{ github.repository }}:${{steps.meta.outputs.tags}}
                      Закончился с ✅
                      [Ссылка на изменения](https://github.com/${{ github.repository }}/commit/${{github.sha}})

            - name: Send Bad Notification
              uses: appleboy/telegram-action@master
              if: failure() && steps.build.outcome == 'failure'
              with:
                  to: ${{ secrets.TELEGRAM_CHAT }}
                  token: ${{ secrets.TELEGRAM_TOKEN }}
                  message: |
                      Билд образа ${{ github.repository }}:${{steps.meta.outputs.tags}}
                      Закончился с ❌
                      [Ссылка на джобу](https://github.com/${{ github.repository }}/actions/runs/${{github.run_id}})
