name: build-push-dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./Dockerfile
        tags: frontend:latest-dev
        push: true
    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag nikdemi/rabotyagi-frontend:latest-dev
      
    # - uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4

    # - name: 'Upload Artifact'
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: my-artifact
    #     path: my_file.txt
    #     retention-days: 5